version: '3.3'

services:
  tomcat:
    image: tomcat:9.0.43-jdk11-openjdk-buster
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      # - ./webapps:/usr/local/tomcat/webapps
      # OU default tomcat
      - ./webapps.dist:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
